### ISSUE TITLE
Insecure curl settings and using curl directly

### ISSUE THREAD

**Issue by tmuras** [miniOrangeDev/moodle-auth_mo_api#1]
Hello,

There are 2 related issues herel
1. The plugin uses curl directly,which means that Moodle config settings like proxy will be ignored.
2. curl is configured in insecure way:

        curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false );
        // Required for https urls.
        curl_setopt ( $ch, CURLOPT_SSL_VERIFYHOST, false);

**Comment by miniOrangeDev** [comment]
Hello
We have made the required changes in the new version of the plugin following the moodle guidelines.
We are not using curl anymore in our plugin.
